kind: pipeline
name: default

steps:
- name: build
  image: maven:latest
  commands:
  - echo "Compiling the code..."
  - mvn clean package

- name: test
  image: maven:latest
  commands:
  - echo "Running tests"
  - java -cp target/helloworld-1.1.jar com.coveros.demo.helloworld.HelloWorld
